name: Participation Logger

on:
  push:
    branches:
      - main

jobs:
  logging:
    name: Logging another participation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: "Run Workflow: changed-files"
        uses: tj-actions/changed-files@v1.2.0
        id: changed-files

      - name: Show output
        run: |
          echo "${{ toJSON(steps.changed-files.outputs) }}"
          echo "${{ steps.changed-files.outputs }}"
          echo "${{ github.repository }}"
          echo "${{ toJSON(github.event) }}"
          echo "${{ github.actor }}" 

      - name: Check participation from changed files
        run: node index.js
        with:
          addedFiles: "${{ steps.changed-files.outputs.added_files }}"
          deletedFiles: "${{ steps.changed-files.outputs.deleted_files }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" # 얜 기본 환경변수로 제공되지 않기 때문.
