name: Participation Checker

on:
  push:
    branches:
      - main

jobs:
  logging:
    name: Start checking participation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: "Run Workflow: changed-files"
        uses: tj-actions/changed-files@v1.2.0
        id: changed-files

      - name: Show output
        run: |
          echo "${{ github.repository }}"
          echo "${{ github.actor }}"
          echo "${{ steps.changed-files.outputs.added_files }}"
          echo "${{ steps.changed-files.outputs.deleted_files }}"

      - name: Check participation from changed files
        run: |
          npm ci
          node index.js
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" # 얜 기본 환경변수로 제공되지 않기 때문.
          ADDED_FILES: "${{ steps.changed-files.outputs.added_files }}"
          DELETED_FILES: "${{ steps.changed-files.outputs.deleted_files }}"
